# Route for Streamlit UI Application (OpenShift)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: ls4-jan212026-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ls4-jan212026-3
  name: ls4-jan212026-3
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ls4-jan212026-3
    weight: 100
  wildcardPolicy: None

