# Ollama Server Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ls4-jan212026-3-ollama
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ls4-jan212026-3-ollama
    app.kubernetes.io/part-of: ls4-jan212026-3
    app.kubernetes.io/component: ollama
  name: ls4-jan212026-3-ollama
spec:
  ports:
    - name: http
      port: 11434
      protocol: TCP
      targetPort: 11434
  selector:
    app.kubernetes.io/instance: ls4-jan212026-3-ollama
  type: ClusterIP
